***********************************************************;
*  LESSON 1, PRACTICE 2                                   *;
*  a) Examine the program and answer the following        *;
*     questions.                                          *;
*     1) Which statements are compile-time only?          *;
*     2) What will be assigned for the length of Size?    *;
*  b) Run the program and examine the results.            *;
*  c) Modify the program to resolve the truncation of     *;
*     Size. Read the first 5 rows from the input table.   *;
*  d) Add PUTLOG statements to provide the following      *;
*     information in the log:                             *;
*     1) Immediately after the SET statement, write START *;
*        DATA STEP ITERATION to the log as a color-coded  *;
*        note.                                            *;
*     2) After the Type= assignment statement, write the  *;
*        value of Type to the log.                        *;
*     3) At the end of the DATA step, write the contents  *;
*        of the PDV to the log.                           *;
*  e) Run the program and read the log to examine the     *;
*     messages written during execution.                  *;
***********************************************************;

data np_parks;
	set pg2.np_final;
	keep Region ParkName AvgMonthlyVisitors Acres Size;
    where Type="PARK";
	format AvgMonthlyVisitors Acres comma10.;
	length size $ 6;
    Type=propcase(Type);
    putlog Type;
	AvgMonthlyVisitors=sum(DayVisits,Campers,OtherLodging)/12;
	if Acres<1000 then Size="Small";
	else if Acres<100000 then Size="Medium";
	else Size="Large";
	putlog _all_;
run;
